[feat] #21 Room List API
TelePigeon/TelePigeon-Server pull request #32
Opened 2024-05-23 08:46 UTC by kmjenny

## Related issue 🛠
- closed #21 

## Work Description ✏️
- Room List 가져오는 API
- 해당 API 확인 테스트코드

## Uncompleted Tasks 😅
[//]: # (없다면 N/A)
- [ ] 우울감 측정 AI 추가 시 emotion 업데이트

## To Reviewers 📢
<img width="596" alt="스크린샷 2024-05-23 오후 5 44 20" src="https://github.com/TelePigeon/TelePigeon-Server/assets/88226911/5b98e840-2f79-42ed-9435-98ef570f95f2">
테스트코드 돌리면 나오는 결과입니당

2024-05-26 11:23 UTC, tkdwns414 requested changes
리뷰 확인해주세요~

2024-05-26 11:23 UTC, tkdwns414 commented on src/main/java/com/telepigeon/server/domain/Profile.java
> +    }
왜 위의 create에 relation이 생기는게 아니라 createTest에만 relation이 있는거죠? 어떤 상황인지 이해가 잘 안 갑니다.

2024-05-26 11:23 UTC, tkdwns414 commented on src/main/java/com/telepigeon/server/controller/RoomController.java
> +        return ResponseEntity.created(location).build();
사소한 부분이기는 한데 location을 바로 사용할거라면 할당하는 부분을 없애서 할당 비용을 없애고 created()안에 바로 URI.create를 사용할 수 있을 것 같아요.

2024-05-26 11:23 UTC, tkdwns414 commented on src/main/java/com/telepigeon/server/dto/room/response/RoomListDto.java
> +        Integer sentence
저희가 API 명세서를 최종 수정할 때 실수가 있었나봐요. 리스트를 반환할 때는 data에 바로 [] 형태가 아니라 {} 안에 rooms:[] 와 같은 형식을 사용하기로 했었는데 놓쳤던 것 같습니다. 그래서 수정된 명세와 같이 바뀌어야하는데 현재 형태가 밖에서 stream을 사용하는 형태라 어떤 방식이 좋을지 고민이 됩니다.

그리고 DTO의 수를 줄이기 위해 ListDto 같은 경우에는 ListDto 내부 이너클래스로 Dto를 하나 만들어서 해결하는 방식이 좋을 것 같다고 요즘 생각하는 중인데 어떻게 생각하시나요? 의견 달아주시면 감사하겠습니다

2024-05-26 11:23 UTC, tkdwns414 commented on src/main/java/com/telepigeon/server/repository/ProfileRepository.java
> +    List<Profile> findByUserId(Long userId);
JPA에서는 findBy 접두사와 findAllBy 접두사를 동일취급하지만 보통 JPA에서 여러개를 가져올 때는 findAll을 접두사로 사용하는 경우가 많은 것 같습니다. 그리고 아래에서 사용하시는 메소드도 findAll~로 생성돼있고요. 저희끼리도 정해서 하나로 통일할 필요가 있어보여요!

2024-05-26 11:23 UTC, tkdwns414 commented on src/main/java/com/telepigeon/server/service/profile/ProfileRetriever.java
> +
보통 List를 반환하는 경우에는 안에 내용이 없다고 에러를 일으키지 않습니다. 안에 내용이 없어서 에러를 일으킨다면 모든 유저가 처음에 회원가입하자마자 에러를 맞닥뜨리게 될 것 같아요

2024-05-26 11:23 UTC, tkdwns414 commented on src/main/java/com/telepigeon/server/service/room/RoomSaver.java
> +import org.springframework.beans.factory.annotation.Autowired;
안 쓰는 임포트는 삭제해주세요

2024-05-26 11:23 UTC, tkdwns414 commented on src/main/java/com/telepigeon/server/service/room/RoomService.java
> +    public RoomInfoDto getRoomInfo(final Long roomId) {
단순 조회 메소드도 Transactional(readOnly=true)를 사용해주면 더티체킹(업데이트 감지)을 하지 않아서 성능적 이득이 있습니다!

2024-05-26 11:23 UTC, tkdwns414 commented on src/main/java/com/telepigeon/server/service/worry/WorryRetriever.java
> +import com.telepigeon.server.exception.code.NotFoundErrorCode;
마찬가지로 안 쓰는 import들 다 지워주세요

2024-05-26 11:23 UTC, tkdwns414 commented on src/test/java/com/telepigeon/server/roomTest/RoomServiceTest.java
>          Assertions.assertEquals(room.getName(), createdRoom.getName());
이거 지금 봤는데 Assertions를 assertj의 것을 꺼내오는 것은 어떨까요? 아래에 정보를 출력해 확인도 Assertions를 이용해서 확인하는게 좋을 것 같습니다.

2024-05-26 11:23 UTC, tkdwns414 commented on src/test/java/com/telepigeon/server/roomTest/RoomServiceTest.java
>      public void checkRoomInDB() {
지난번에 확인을 제가 확인을 제대로 못했던 것 같습니다. 테스트코드를 작성할 때는 given when then 구조를 사용해서 given 부분에서 필요한 설정을 다 하고(여기서는 mock), 그 이후에 테스트하고 싶은 코드를 실행하고, 마지막에 Assert를 해주시는 방식으로 구현해주시면 될 것 같습니다. 

매번 사용 직전에 mock을 하시면 어떤 테스트를 진행하는지 확인하기 조금 힘든 것 같아요. 다시 작성해주실 수 있으실까요?

2024-05-27 04:42 UTC, minwoo0419 approved these changes
고생 많으셨습니다. 상준님이 다신 리뷰 말고는 추가적인 수정사항이 없는 것 같네요! 따로 더 달진 않겠습니다!

2024-05-27 07:06 UTC, kmjenny commented on src/main/java/com/telepigeon/server/domain/Profile.java
> +    }
테스트 때 쓰려고 만들었다가 필요가 없어졌는데 못 지웠네요.. 지우겠습니당

2024-05-27 07:09 UTC, kmjenny commented on src/main/java/com/telepigeon/server/repository/ProfileRepository.java
> +    List<Profile> findByUserId(Long userId);
findAll로 통일하겠습니당

2024-05-28 05:53 UTC, minwoo0419 approved these changes
고생하셨습니다!

2024-05-28 05:53 UTC, minwoo0419 commented on src/main/java/com/telepigeon/server/controller/RoomController.java
> +    public ResponseEntity<List<RoomListDto>> getAllRooms(@UserId Long userId) {
RoomListDto가 room의 list를 반환하는 것 같은데 한번 더 RoomListDto의 List로 반환하는 이유가 무엇인가요??

2024-05-28 05:53 UTC, minwoo0419 commented on src/main/java/com/telepigeon/server/service/profile/ProfileRetriever.java
> +    public List<Profile> findAll() {
추가 감사합니다

2024-05-28 05:55 UTC, kmjenny commented on src/main/java/com/telepigeon/server/controller/RoomController.java
> +    public ResponseEntity<List<RoomListDto>> getAllRooms(@UserId Long userId) {
수정안했네여.. 수정해서 바로 올리겠습니당

2024-05-28 10:05 UTC, minwoo0419 approved these changes
수정 확인했습니다~

2024-05-28 10:26 UTC, tkdwns414 commented on src/main/java/com/telepigeon/server/domain/Profile.java
> +    }
제가 정적 팩토리 메소드의 사용을 보장하려고 생성자를 private으로 만들자고 해서 일어난 일이군요... 대안을 한 번 찾아보겠습니다!

2024-05-28 10:29 UTC, tkdwns414 approved these changes
몇 개 남은 수정만 더 하고 머지 해주시면 될 것 같아요~

2024-05-28 10:31 UTC, merged