[feat] open ai 연결 및 질문 생성 구현
TelePigeon/TelePigeon-Server pull request #43
Opened 2024-06-01 10:51 UTC by minwoo0419

## Related issue 🛠
[//]: # (해당하는 이슈 번호 달아주기)
- closed #42

## Work Description ✏️
[//]: # (작업 내용 간단 소개)
- open ai 연결
- 질문 자동 생성 구현

## Uncompleted Tasks 😅
[//]: # (없다면 N/A)
- [ ] 프롬프팅 더 수정 해야 함

## To Reviewers 📢
[//]: # (reviewer가 알면 좋은 내용들)

2024-06-02 07:35 UTC, tkdwns414 requested changes

2024-06-02 07:35 UTC, tkdwns414 commented on src/main/java/com/telepigeon/server/domain/Profile.java
> +    }
저희 생성자로 안하고 정적팩토리 메소드로 통일하기로 했는데 인자 추가하는게 필요한 경우에는 오버로딩 이용해서 정적팩토리 메소드 만들어주세요. 기존 private 생성자에 추가 필드 만들어주시면 됩니다.

2024-06-02 07:35 UTC, tkdwns414 commented on src/main/java/com/telepigeon/server/service/openAi/OpenAiService.java
> +    }
확인했습니다. 월요일에 같이 찾아봐용.

2024-06-03 11:44 UTC, tkdwns414 approved these changes

2024-06-03 13:10 UTC, kmjenny reviewed
최고에요 (∗'ര ᎑ ര`∗)

2024-06-03 13:11 UTC, merged