[fix] Room 입장 분기처리 추가
TelePigeon/TelePigeon-Server pull request #59
Opened 2024-06-05 07:18 UTC by kmjenny

## Related issue 🛠
[//]: # (해당하는 이슈 번호 달아주기)
- closed #58 

## Work Description ✏️
[//]: # (작업 내용 간단 소개)
- 분기처리 부분 service에 추가
- build.gradle 의존성 추가

2024-06-05 10:05 UTC, minwoo0419 approved these changes
고생하셨습니다

2024-06-05 10:05 UTC, minwoo0419 commented on src/main/java/com/telepigeon/server/exception/code/ForbiddenErrorCode.java
> +    ENTER_FORBIDDEN(HttpStatus.FORBIDDEN, "error", "이미 매칭이 완료된 방입니다."),
이것도 마찬가지로 error가 아닌 conflict인 것같은데 어떻게생각하시나요?

2024-06-05 10:06 UTC, tkdwns414 requested changes
확인 부탁드립니다

2024-06-05 10:06 UTC, tkdwns414 commented on src/main/java/com/telepigeon/server/exception/code/ForbiddenErrorCode.java
> +    ENTER_FORBIDDEN(HttpStatus.FORBIDDEN, "error", "이미 매칭이 완료된 방입니다."),
forbidden은 권한이 부족할 때 내려주는 status code라서 400이나 409가 더 알맞을 것 같습니다!

2024-06-06 05:20 UTC, minwoo0419 approved these changes
conflict해결 잘해서 머지 부탁드릴게여

2024-06-06 05:25 UTC, merged