[feat] Worry API 생성
TelePigeon/TelePigeon-Server pull request #69
Opened 2024-06-05 14:59 UTC by tkdwns414

## Related issue 🛠
[//]: # (해당하는 이슈 번호 달아주기)
- closed #66

## Work Description ✏️
[//]: # (작업 내용 간단 소개)
- Worry List
- Worry Create
- Worry Delete

## Uncompleted Tasks 😅
[//]: # (없다면 N/A)
- [ ] Worry Cron

## To Reviewers 📢
[//]: # (reviewer가 알면 좋은 내용들)
worry 생성시 URI는 Worry에 접근할 수 있는 URI(list)로 설정해주었습니다

2024-06-05 15:21 UTC, kmjenny approved these changes
대단해요 ! ദ്ദി´･_･`)

2024-06-05 15:23 UTC, minwoo0419 requested changes
확인 부탁드릴게여

2024-06-05 15:23 UTC, minwoo0419 commented on src/main/java/com/telepigeon/server/controller/WorryController.java
> +            @RequestBody final WorryCreateDto request
Valid를 사용해서 인자형식이 제대로 들어오는지 확인하면 좋을 것 같아요

2024-06-05 15:23 UTC, minwoo0419 commented on src/main/java/com/telepigeon/server/service/worry/WorryService.java
> +                String.join("|", request.times()),
명세서에는 , 로되있는데 확인 부탁드립니다

2024-06-05 15:30 UTC, minwoo0419 commented on src/main/java/com/telepigeon/server/service/worry/WorryService.java
> +                String.join("|", request.times()),
아 db에 저장할때 하는거군요. 잘못봤습니다!

2024-06-06 04:47 UTC, tkdwns414 commented on src/main/java/com/telepigeon/server/service/worry/WorryService.java
> +                String.join("|", request.times()),
혼날래요

2024-06-06 05:18 UTC, minwoo0419 approved these changes
고생하셨습니다

2024-06-06 05:43 UTC, merged